name: George's Daily Commit

on:
  schedule:
    - cron: '0 * * * *'  # 00:45 UTC = 08:45 SGT, SGT is 8 hours ahead of UTC, S means Singapore Time, U means Coordinated Universal Time
    # - cron: '18 17 2 1 *'  # 2024-01-02T17:18:19Z

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Create file and commit
        run: |
          FILE="commit_number.md"
          if [ ! -f "$FILE" ]; then
            echo "..." > "$FILE"
            echo "commit number: 1" >> "$FILE"
          else
            CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
            if [ -z "$CURRENT_COUNT" ]; then
              CURRENT_COUNT=0
            fi
            NEXT_COUNT=$((CURRENT_COUNT + 1))
            sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
          fi
          git config --global user.name "George"
          git config --global user.email "nunchakus2012@hotmail.com"
          git add "$FILE"
          git commit -m "....."
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Nunchakus888/Nunchakus888.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
